name: CD Pipeline

on:
    workflow_run:
        workflows: ["CI Pipeline"]
        types:
            - completed

jobs:
    build:
        runs-on: self-hosted

        steps:
            - name: Login DockerHub
              env:
                  DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
                  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
              run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            - name: Pull Docker image
              run: sudo docker pull sachanritik1/youtube-express:latest
            - name: Delete Old docker container
              run: sudo docker rm -f youtube-express-container || true
            - name: Run Docker Container
              run: sudo docker run -d -p 5000:5000 --name youtube-express-container sachanritik1/youtube-express
